import { Inter } from "next/font/google";
import "./globals.css";
import MainContainer from "@/components/infra/MainContainer/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainContainer>
          {children}
        </MainContainer>
      </body>
    </html>
  );
}
